import React, { useState } from "react";
import ProductItem from "./ProductItem"; // Assuming ProductItem is in the same directory

const featuredProducts = [
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  },
  {
    imageUrl: "img/product-1-1.jpg",
    imageHoverUrl: "img/product-1-2.jpg",
    category: "Clothing",
    title: "Colourful Pattern Shirts",
    rating: 5,
    newPrice: "$238.8",
    oldPrice: "$245.8",
    badge: "Hot",
    badgeColor: "light-pink",
  },
  {
    imageUrl: "img/product-2-1.jpg",
    imageHoverUrl: "img/product-2-2.jpg",
    category: "Clothing",
    title: "Elegant Fashion Dress",
    rating: 4,
    newPrice: "$120.5",
    oldPrice: "$130.5",
    badge: "New",
    badgeColor: "blue",
  },
  {
    imageUrl: 'img/product-3-1.jpg',
    imageHoverUrl: 'img/product-3-2.jpg',
    category: 'Accessories',
    title: 'Leather Handbags',
    rating: 4.5,
    newPrice: '$120.0',
    oldPrice: '$130.0',
    badge: 'New',
    badgeColor: 'light-blue',
  }
];

const PRODUCTS_PER_PAGE = 12; // Number of products per page

function Mainshop() {
  const [currentPage, setCurrentPage] = useState(1);

  const totalPages = Math.ceil(featuredProducts.length / PRODUCTS_PER_PAGE);

  const handlePageChange = (page) => {
    setCurrentPage(page);
  };

  const getCurrentPageProducts = () => {
    const startIndex = (currentPage - 1) * PRODUCTS_PER_PAGE;
    const endIndex = startIndex + PRODUCTS_PER_PAGE;
    return featuredProducts.slice(startIndex, endIndex);
  };

  return (
    <div>
      <section className="breadcrumb">
        <ul className="breadcrumb__list container flex container">
          <li><a href="index" className="breadcrumb__link">Home</a></li>
          <li><span className="braedcrumb__link">&gt;</span></li>
          <li><span className="braedcrumb__link">Shop</span></li>
        </ul>
      </section>

      <section className="products section--lg container">
        <p className="total__products">
          We found <span>{featuredProducts.length}</span> items for you!
        </p>

        <div className="tab__items">
          <div className="product__container grid">
            {getCurrentPageProducts().map((product, index) => (
              <ProductItem key={index} product={product} /> // Passing product data to ProductItem
            ))}
          </div>
        </div>

        <ul className="pagination">
          <li>
            <a
              href="#"
              className={`pagination__link iconl ${currentPage === 1 ? "disabled" : ""}`}
              onClick={() => currentPage > 1 && handlePageChange(currentPage - 1)}
              >
              <i className="fi-rs-angle-double-small-left"></i>
            </a>
          </li>
          {Array.from({ length: totalPages }, (_, index) => (
            <li key={index}>
              <a
                href="#"
                className={`pagination__link ${currentPage === index + 1 ? "active" : ""}`}
                onClick={() => handlePageChange(index + 1)}
              >
                {index + 1}
              </a>
            </li>
          ))}
          <li>
            <a
              href="#"
              className={`pagination__link icon ${currentPage === totalPages ? "disabled" : ""}`}
              onClick={() => currentPage < totalPages && handlePageChange(currentPage + 1)}
              >
              <i className="fi-rs-angle-double-small-right"></i>
            </a>
          </li>
        </ul>
      </section>
    </div>
  );
}

export default Mainshop;
